apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"minio-service","namespace":"storage"},"spec":{"ports":[{"name":"api","nodePort":30900,"port":9000,"targetPort":9000},{"name":"console","nodePort":30901,"port":9001,"targetPort":9001}],"selector":{"app":"minio"},"type":"NodePort"}}
  creationTimestamp: "2026-06-26T11:22:03Z"
  name: minio-service
  namespace: storage
  resourceVersion: "23027"
  uid: 008c730e-822e-4e34-a549-fd71ef2f843d
spec:
  clusterIP: 10.99.203.2
  clusterIPs:
  - 10.99.203.2
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api
    nodePort: 30900
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    nodePort: 30901
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
